# Generated by Django 5.2.16 on 2026-07-26 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_initial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Начальное количество')),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оставшееся количество')),
                ('purchased_at', models.DateTimeField(verbose_name='Дата покупки')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок годности')),
                ('storage_location', models.CharField(choices=[('fridge', 'Холодильник'), ('freezer', 'Морозильник'), ('kitchen_cabinet', 'Кухонный шкаф'), ('pantry', 'Кладовая'), ('bathroom', 'Ванная'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Место хранения')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Партия товара',
                'verbose_name_plural': 'Партии товаров',
                'ordering': ['expires_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('default_unit', models.CharField(choices=[('piece', 'Штука'), ('gram', 'Грамм'), ('kilogram', 'Килограмм'), ('milliliter', 'Миллилитр'), ('liter', 'Литр'), ('package', 'Упаковка')], default='piece', max_length=20, verbose_name='Единица измерения')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный остаток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('purchase', 'Покупка/Пополнение'), ('consume', 'Расход'), ('discard', 'Выбрасывание'), ('correction', 'Ручная корректировка'), ('transfer', 'Перемещение')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='myhousehold.batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='myhousehold.product')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='myhousehold.product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'name'], name='myhousehold_user_id_9cc435_idx'),
        ),
    ]
